name: Build and Deploy Django App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect static files
        env:
          SECRET_KEY: dummy-secret-key
          DEBUG: False
          ALLOWED_HOSTS: localhost
          DATABASE_ENGINE: django.db.backends.sqlite3
          DATABASE_NAME: db.sqlite3
          DATABASE_USER: ""
          DATABASE_PASSWORD: ""
          DATABASE_HOST: ""
          DATABASE_PORT: ""
        run: |
          python manage.py collectstatic --noinput

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: vehicle-inventory-api-sathwickhk
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}